version: "3.9"
services:
    rabbitmq:
        image: rabbitmq:3.9.7-management-alpine
        container_name: rabbitmq
        ports:
            - "5672:5672" # AMQP
            - "15672:15672" # HTTP (Management)
